<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>注册测试用例</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2.2"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    
<style type="text/css" media="screen">
body        { font-family: Microsoft YaHei,Tahoma,arial,helvetica,sans-serif;padding: 20px; font-size: 120%; }
table       { font-size: 100%; }
/* -- heading ---------------------------------------------------------------------- */
.heading {
    margin-top: 0ex;
    margin-bottom: 1ex;
}
.heading .description {
    margin-top: 4ex;
    margin-bottom: 6ex;
}
/* -- report ------------------------------------------------------------------------ */
#total_row  { font-weight: bold; }
.passCase   { color: #5cb85c; }
.failCase   { color: #d9534f; font-weight: bold; }
.errorCase  { color: #f0ad4e; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }
</style>

</head>
<body >
<script language="javascript" type="text/javascript">
output_list = Array();
/*level 调整增加只显示通过用例的分类 --Findyou
0:Summary //all hiddenRow
1:Failed  //pt hiddenRow, ft none
2:Pass    //pt none, ft hiddenRow
3:All     //pt none, ft none
*/
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level == 2 || level == 0 ) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level < 2) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
    }
    //加入【详细】切换文字变化 --Findyou
    detail_class=document.getElementsByClassName('detail');
	//console.log(detail_class.length)
	if (level == 3) {
		for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="收起"
		}
	}
	else{
			for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="详细"
		}
	}
}
function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {
        //ID修改 点 为 下划线 -Findyou
        tid0 = 't' + cid.substr(1) + '_' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];
        //修改点击无法收起的BUG，加入【详细】切换文字变化 --Findyou
        if (toHide) {
            document.getElementById(tid).className = 'hiddenRow';
            document.getElementById(cid).innerText = "详细"
        }
        else {
            document.getElementById(tid).className = '';
            document.getElementById(cid).innerText = "收起"
        }
    }
}
function html_escape(s) {
    s = s.replace(/&/g,'&amp;');
    s = s.replace(/</g,'&lt;');
    s = s.replace(/>/g,'&gt;');
    return s;
}
</script>
<div class='heading'>
<h1 style="font-family: Microsoft YaHei">注册测试用例</h1>
<p class='attribute'><strong>测试人员 : </strong> wyr</p>
<p class='attribute'><strong>开始时间 : </strong> 2019-07-27 20:19:24</p>
<p class='attribute'><strong>合计耗时 : </strong> 0:00:14.398667</p>
<p class='attribute'><strong>测试结果 : </strong> 共 65，通过 14，失败 37，错误 14，通过率= 21.54%</p>

<p class='description'></p>
</div>


<p id='show_detail_line'>
<a class="btn btn-primary" href='javascript:showCase(0)'>概要{ 21.54% }</a>
<a class="btn btn-danger" href='javascript:showCase(1)'>失败{ 37 }</a>
<a class="btn btn-success" href='javascript:showCase(2)'>通过{ 14 }</a>
<a class="btn btn-info" href='javascript:showCase(3)'>所有{ 65 }</a>
</p>
<table id='result_table' class="table table-condensed table-bordered table-hover">
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row' class="text-center success" style="font-weight: bold;font-size: 16px;">
    <td>用例集/测试用例</td>
    <td>总计</td>
    <td>通过</td>
    <td>失败</td>
    <td>错误</td>
    <td>详细</td>
</tr>

<tr class='failClass warning'>
    <td>test_02_login.TestRegister</td>
    <td class="text-center">5</td>
    <td class="text-center">4</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center"><a href="javascript:showClassDetail('c1',5)" class="detail" id='c1'>详细</a></td>
</tr>

<tr id='ft1_1' class='none'>
    <td class='failCase'><div class='testcase'>test_register_1_正常登录</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_1'>失败</button>
    <div id='div_ft1_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_1'>失败</button>
    <div id='div_ft1_1' class="collapse in" align="left">
    <pre>
    
ft1_1: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_02_login.py", line 55, in test_register
    raise e
  File "G:\qianchengdai\cases\test_02_login.py", line 48, in test_register
    self.assertEqual(val['expected'],actual_result.text)
AssertionError: '{"status":1,"code":"10001","data":null,"msg":"登录成功"}' != '{"status":0,"code":"20111","data":null,"msg":"用户名或密码错误"}'
- {"status":1,"code":"10001","data":null,"msg":"登录成功"}
?           ^          ^^^                      ^^^^
+ {"status":0,"code":"20111","data":null,"msg":"用户名或密码错误"}
?           ^         ++ ^                      ^^^^^^^^



    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_2' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_register_2_手机号为空</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_3' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_register_3_密码为空</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_4' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_register_4_密码错误</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_5' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_register_5_手机号错误</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr class='failClass warning'>
    <td>test_03_recharge.TestRecharge</td>
    <td class="text-center">15</td>
    <td class="text-center">0</td>
    <td class="text-center">15</td>
    <td class="text-center">0</td>
    <td class="text-center"><a href="javascript:showClassDetail('c2',15)" class="detail" id='c2'>详细</a></td>
</tr>

<tr id='ft2_1' class='none'>
    <td class='failCase'><div class='testcase'>test_register_01_正常登录</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_1'>失败</button>
    <div id='div_ft2_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_1'>失败</button>
    <div id='div_ft2_1' class="collapse in" align="left">
    <pre>
    
ft2_1: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_03_recharge.py", line 94, in test_register
    raise e
  File "G:\qianchengdai\cases\test_03_recharge.py", line 76, in test_register
    self.assertEqual(str(val['expected']),code)
AssertionError: '10001' != '20111'
- 10001
+ 20111



    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_2' class='none'>
    <td class='failCase'><div class='testcase'>test_register_02_充值成功_整数</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_2'>失败</button>
    <div id='div_ft2_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_2'>失败</button>
    <div id='div_ft2_2' class="collapse in" align="left">
    <pre>
    
ft2_2: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_03_recharge.py", line 94, in test_register
    raise e
  File "G:\qianchengdai\cases\test_03_recharge.py", line 76, in test_register
    self.assertEqual(str(val['expected']),code)
AssertionError: '10001' != None


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_3' class='none'>
    <td class='failCase'><div class='testcase'>test_register_03_充值成功_1位小数</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_3'>失败</button>
    <div id='div_ft2_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_3'>失败</button>
    <div id='div_ft2_3' class="collapse in" align="left">
    <pre>
    
ft2_3: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_03_recharge.py", line 94, in test_register
    raise e
  File "G:\qianchengdai\cases\test_03_recharge.py", line 76, in test_register
    self.assertEqual(str(val['expected']),code)
AssertionError: '10001' != None


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_4' class='none'>
    <td class='failCase'><div class='testcase'>test_register_04_充值成功_2位小数</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_4'>失败</button>
    <div id='div_ft2_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_4'>失败</button>
    <div id='div_ft2_4' class="collapse in" align="left">
    <pre>
    
ft2_4: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_03_recharge.py", line 94, in test_register
    raise e
  File "G:\qianchengdai\cases\test_03_recharge.py", line 76, in test_register
    self.assertEqual(str(val['expected']),code)
AssertionError: '10001' != None


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_5' class='none'>
    <td class='failCase'><div class='testcase'>test_register_05_充值成功_50万</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_5'>失败</button>
    <div id='div_ft2_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_5'>失败</button>
    <div id='div_ft2_5' class="collapse in" align="left">
    <pre>
    
ft2_5: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_03_recharge.py", line 94, in test_register
    raise e
  File "G:\qianchengdai\cases\test_03_recharge.py", line 76, in test_register
    self.assertEqual(str(val['expected']),code)
AssertionError: '10001' != None


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_6' class='none'>
    <td class='failCase'><div class='testcase'>test_register_06_手机号为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_6'>失败</button>
    <div id='div_ft2_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_6'>失败</button>
    <div id='div_ft2_6' class="collapse in" align="left">
    <pre>
    
ft2_6: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_03_recharge.py", line 94, in test_register
    raise e
  File "G:\qianchengdai\cases\test_03_recharge.py", line 76, in test_register
    self.assertEqual(str(val['expected']),code)
AssertionError: '20103' != None


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_7' class='none'>
    <td class='failCase'><div class='testcase'>test_register_07_手机号_不足11位</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_7'>失败</button>
    <div id='div_ft2_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_7'>失败</button>
    <div id='div_ft2_7' class="collapse in" align="left">
    <pre>
    
ft2_7: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_03_recharge.py", line 94, in test_register
    raise e
  File "G:\qianchengdai\cases\test_03_recharge.py", line 76, in test_register
    self.assertEqual(str(val['expected']),code)
AssertionError: '20109' != None


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_8' class='none'>
    <td class='failCase'><div class='testcase'>test_register_08_手机号_超过11位</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_8' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_8'>失败</button>
    <div id='div_ft2_8' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_8' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_8'>失败</button>
    <div id='div_ft2_8' class="collapse in" align="left">
    <pre>
    
ft2_8: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_03_recharge.py", line 94, in test_register
    raise e
  File "G:\qianchengdai\cases\test_03_recharge.py", line 76, in test_register
    self.assertEqual(str(val['expected']),code)
AssertionError: '20109' != None


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_9' class='none'>
    <td class='failCase'><div class='testcase'>test_register_09_手机号_不存在</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_9' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_9'>失败</button>
    <div id='div_ft2_9' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_9' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_9'>失败</button>
    <div id='div_ft2_9' class="collapse in" align="left">
    <pre>
    
ft2_9: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_03_recharge.py", line 94, in test_register
    raise e
  File "G:\qianchengdai\cases\test_03_recharge.py", line 76, in test_register
    self.assertEqual(str(val['expected']),code)
AssertionError: '20104' != None


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_10' class='none'>
    <td class='failCase'><div class='testcase'>test_register_10_充值金额为0</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_10' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_10'>失败</button>
    <div id='div_ft2_10' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_10' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_10'>失败</button>
    <div id='div_ft2_10' class="collapse in" align="left">
    <pre>
    
ft2_10: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_03_recharge.py", line 94, in test_register
    raise e
  File "G:\qianchengdai\cases\test_03_recharge.py", line 76, in test_register
    self.assertEqual(str(val['expected']),code)
AssertionError: '20117' != None


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_11' class='none'>
    <td class='failCase'><div class='testcase'>test_register_11_充值金额为负数</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_11' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_11'>失败</button>
    <div id='div_ft2_11' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_11' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_11'>失败</button>
    <div id='div_ft2_11' class="collapse in" align="left">
    <pre>
    
ft2_11: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_03_recharge.py", line 94, in test_register
    raise e
  File "G:\qianchengdai\cases\test_03_recharge.py", line 76, in test_register
    self.assertEqual(str(val['expected']),code)
AssertionError: '20117' != None


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_12' class='none'>
    <td class='failCase'><div class='testcase'>test_register_12_充值金额为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_12' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_12'>失败</button>
    <div id='div_ft2_12' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_12' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_12'>失败</button>
    <div id='div_ft2_12' class="collapse in" align="left">
    <pre>
    
ft2_12: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_03_recharge.py", line 94, in test_register
    raise e
  File "G:\qianchengdai\cases\test_03_recharge.py", line 76, in test_register
    self.assertEqual(str(val['expected']),code)
AssertionError: '20115' != None


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_13' class='none'>
    <td class='failCase'><div class='testcase'>test_register_13_充值金额_3位小数</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_13' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_13'>失败</button>
    <div id='div_ft2_13' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_13' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_13'>失败</button>
    <div id='div_ft2_13' class="collapse in" align="left">
    <pre>
    
ft2_13: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_03_recharge.py", line 94, in test_register
    raise e
  File "G:\qianchengdai\cases\test_03_recharge.py", line 76, in test_register
    self.assertEqual(str(val['expected']),code)
AssertionError: '20116' != None


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_14' class='none'>
    <td class='failCase'><div class='testcase'>test_register_14_充值金额_大于50万</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_14' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_14'>失败</button>
    <div id='div_ft2_14' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_14' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_14'>失败</button>
    <div id='div_ft2_14' class="collapse in" align="left">
    <pre>
    
ft2_14: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_03_recharge.py", line 94, in test_register
    raise e
  File "G:\qianchengdai\cases\test_03_recharge.py", line 76, in test_register
    self.assertEqual(str(val['expected']),code)
AssertionError: '20117' != None


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_15' class='none'>
    <td class='failCase'><div class='testcase'>test_register_15_充值金额_非数字</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_15' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_15'>失败</button>
    <div id='div_ft2_15' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_15' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_15'>失败</button>
    <div id='div_ft2_15' class="collapse in" align="left">
    <pre>
    
ft2_15: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_03_recharge.py", line 94, in test_register
    raise e
  File "G:\qianchengdai\cases\test_03_recharge.py", line 76, in test_register
    self.assertEqual(str(val['expected']),code)
AssertionError: '20118' != None


    </pre>
    </div>
    </td>
</tr>

<tr class='failClass warning'>
    <td>test_04_add.TestAdd</td>
    <td class="text-center">16</td>
    <td class="text-center">0</td>
    <td class="text-center">16</td>
    <td class="text-center">0</td>
    <td class="text-center"><a href="javascript:showClassDetail('c3',16)" class="detail" id='c3'>详细</a></td>
</tr>

<tr id='ft3_1' class='none'>
    <td class='failCase'><div class='testcase'>test_register_01_正常登录</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_1'>失败</button>
    <div id='div_ft3_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_1'>失败</button>
    <div id='div_ft3_1' class="collapse in" align="left">
    <pre>
    
ft3_1: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_04_add.py", line 55, in test_register
    raise e
  File "G:\qianchengdai\cases\test_04_add.py", line 48, in test_register
    self.assertEqual(val['expected'],actual_result.text)
AssertionError: 10001 != '{"status":0,"code":"20111","data":null,"msg":"用户名或密码错误"}'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_2' class='none'>
    <td class='failCase'><div class='testcase'>test_register_02_加标</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_2'>失败</button>
    <div id='div_ft3_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_2'>失败</button>
    <div id='div_ft3_2' class="collapse in" align="left">
    <pre>
    
ft3_2: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_04_add.py", line 55, in test_register
    raise e
  File "G:\qianchengdai\cases\test_04_add.py", line 48, in test_register
    self.assertEqual(val['expected'],actual_result.text)
AssertionError: 10001 != '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_3' class='none'>
    <td class='failCase'><div class='testcase'>test_register_03_借款人id为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_3'>失败</button>
    <div id='div_ft3_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_3'>失败</button>
    <div id='div_ft3_3' class="collapse in" align="left">
    <pre>
    
ft3_3: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_04_add.py", line 55, in test_register
    raise e
  File "G:\qianchengdai\cases\test_04_add.py", line 48, in test_register
    self.assertEqual(val['expected'],actual_result.text)
AssertionError: 20103 != '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_4' class='none'>
    <td class='failCase'><div class='testcase'>test_register_04_标题为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_4'>失败</button>
    <div id='div_ft3_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_4'>失败</button>
    <div id='div_ft3_4' class="collapse in" align="left">
    <pre>
    
ft3_4: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_04_add.py", line 55, in test_register
    raise e
  File "G:\qianchengdai\cases\test_04_add.py", line 48, in test_register
    self.assertEqual(val['expected'],actual_result.text)
AssertionError: 20103 != '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_5' class='none'>
    <td class='failCase'><div class='testcase'>test_register_05_借款金额为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_5'>失败</button>
    <div id='div_ft3_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_5'>失败</button>
    <div id='div_ft3_5' class="collapse in" align="left">
    <pre>
    
ft3_5: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_04_add.py", line 55, in test_register
    raise e
  File "G:\qianchengdai\cases\test_04_add.py", line 48, in test_register
    self.assertEqual(val['expected'],actual_result.text)
AssertionError: 20103 != '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_6' class='none'>
    <td class='failCase'><div class='testcase'>test_register_06_年利率为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_6'>失败</button>
    <div id='div_ft3_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_6'>失败</button>
    <div id='div_ft3_6' class="collapse in" align="left">
    <pre>
    
ft3_6: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_04_add.py", line 55, in test_register
    raise e
  File "G:\qianchengdai\cases\test_04_add.py", line 48, in test_register
    self.assertEqual(val['expected'],actual_result.text)
AssertionError: 20103 != '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_7' class='none'>
    <td class='failCase'><div class='testcase'>test_register_07_借款期限为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_7'>失败</button>
    <div id='div_ft3_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_7'>失败</button>
    <div id='div_ft3_7' class="collapse in" align="left">
    <pre>
    
ft3_7: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_04_add.py", line 55, in test_register
    raise e
  File "G:\qianchengdai\cases\test_04_add.py", line 48, in test_register
    self.assertEqual(val['expected'],actual_result.text)
AssertionError: 20103 != '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_8' class='none'>
    <td class='failCase'><div class='testcase'>test_register_08_借款期限类型为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_8' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_8'>失败</button>
    <div id='div_ft3_8' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_8' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_8'>失败</button>
    <div id='div_ft3_8' class="collapse in" align="left">
    <pre>
    
ft3_8: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_04_add.py", line 55, in test_register
    raise e
  File "G:\qianchengdai\cases\test_04_add.py", line 48, in test_register
    self.assertEqual(val['expected'],actual_result.text)
AssertionError: 20103 != '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_9' class='none'>
    <td class='failCase'><div class='testcase'>test_register_09_还款方式为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_9' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_9'>失败</button>
    <div id='div_ft3_9' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_9' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_9'>失败</button>
    <div id='div_ft3_9' class="collapse in" align="left">
    <pre>
    
ft3_9: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_04_add.py", line 55, in test_register
    raise e
  File "G:\qianchengdai\cases\test_04_add.py", line 48, in test_register
    self.assertEqual(val['expected'],actual_result.text)
AssertionError: 20103 != '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_10' class='none'>
    <td class='failCase'><div class='testcase'>test_register_10_竞标天数为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_10' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_10'>失败</button>
    <div id='div_ft3_10' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_10' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_10'>失败</button>
    <div id='div_ft3_10' class="collapse in" align="left">
    <pre>
    
ft3_10: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_04_add.py", line 55, in test_register
    raise e
  File "G:\qianchengdai\cases\test_04_add.py", line 48, in test_register
    self.assertEqual(val['expected'],actual_result.text)
AssertionError: 20103 != '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_11' class='none'>
    <td class='failCase'><div class='testcase'>test_register_11_借款人id为负数</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_11' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_11'>失败</button>
    <div id='div_ft3_11' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_11' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_11'>失败</button>
    <div id='div_ft3_11' class="collapse in" align="left">
    <pre>
    
ft3_11: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_04_add.py", line 55, in test_register
    raise e
  File "G:\qianchengdai\cases\test_04_add.py", line 48, in test_register
    self.assertEqual(val['expected'],actual_result.text)
AssertionError: 20104 != '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_12' class='none'>
    <td class='failCase'><div class='testcase'>test_register_12_借款人id为小数</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_12' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_12'>失败</button>
    <div id='div_ft3_12' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_12' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_12'>失败</button>
    <div id='div_ft3_12' class="collapse in" align="left">
    <pre>
    
ft3_12: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_04_add.py", line 55, in test_register
    raise e
  File "G:\qianchengdai\cases\test_04_add.py", line 48, in test_register
    self.assertEqual(val['expected'],actual_result.text)
AssertionError: 20109 != '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_13' class='none'>
    <td class='failCase'><div class='testcase'>test_register_13_借款金额为负数</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_13' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_13'>失败</button>
    <div id='div_ft3_13' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_13' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_13'>失败</button>
    <div id='div_ft3_13' class="collapse in" align="left">
    <pre>
    
ft3_13: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_04_add.py", line 55, in test_register
    raise e
  File "G:\qianchengdai\cases\test_04_add.py", line 48, in test_register
    self.assertEqual(val['expected'],actual_result.text)
AssertionError: 20106 != '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_14' class='none'>
    <td class='failCase'><div class='testcase'>test_register_14_借款金额为小数</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_14' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_14'>失败</button>
    <div id='div_ft3_14' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_14' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_14'>失败</button>
    <div id='div_ft3_14' class="collapse in" align="left">
    <pre>
    
ft3_14: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_04_add.py", line 55, in test_register
    raise e
  File "G:\qianchengdai\cases\test_04_add.py", line 48, in test_register
    self.assertEqual(val['expected'],actual_result.text)
AssertionError: 20106 != '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_15' class='none'>
    <td class='failCase'><div class='testcase'>test_register_15_借款金额小于1000</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_15' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_15'>失败</button>
    <div id='div_ft3_15' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_15' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_15'>失败</button>
    <div id='div_ft3_15' class="collapse in" align="left">
    <pre>
    
ft3_15: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_04_add.py", line 55, in test_register
    raise e
  File "G:\qianchengdai\cases\test_04_add.py", line 48, in test_register
    self.assertEqual(val['expected'],actual_result.text)
AssertionError: 20106 != '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_16' class='none'>
    <td class='failCase'><div class='testcase'>test_register_16_借款金额等于1000</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_16' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_16'>失败</button>
    <div id='div_ft3_16' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_16' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_16'>失败</button>
    <div id='div_ft3_16' class="collapse in" align="left">
    <pre>
    
ft3_16: 传入的行号有误，行号应为大于1的整数
Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_04_add.py", line 55, in test_register
    raise e
  File "G:\qianchengdai\cases\test_04_add.py", line 48, in test_register
    self.assertEqual(val['expected'],actual_result.text)
AssertionError: 10001 != '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}'


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>test_05_invest.TestInvest</td>
    <td class="text-center">19</td>
    <td class="text-center">0</td>
    <td class="text-center">5</td>
    <td class="text-center">14</td>
    <td class="text-center"><a href="javascript:showClassDetail('c4',19)" class="detail" id='c4'>详细</a></td>
</tr>

<tr id='ft4_1' class='none'>
    <td class='failCase'><div class='testcase'>test_register_01_管理员正常登录</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_1'>失败</button>
    <div id='div_ft4_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_1'>失败</button>
    <div id='div_ft4_1' class="collapse in" align="left">
    <pre>
    
ft4_1: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_05_invest.py", line 80, in test_register
    raise e
  File "G:\qianchengdai\cases\test_05_invest.py", line 73, in test_register
    self.assertEqual(str(val['expected']),code)
AssertionError: '10001' != '20111'
- 10001
+ 20111



    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_2' class='none'>
    <td class='failCase'><div class='testcase'>test_register_02_管理员加标</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_2'>失败</button>
    <div id='div_ft4_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_2'>失败</button>
    <div id='div_ft4_2' class="collapse in" align="left">
    <pre>
    
ft4_2: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_05_invest.py", line 80, in test_register
    raise e
  File "G:\qianchengdai\cases\test_05_invest.py", line 73, in test_register
    self.assertEqual(str(val['expected']),code)
AssertionError: '10001' != None


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_03_管理员审核</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_3'>错误</button>
    <div id='div_ft4_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_3'>错误</button>
    <div id='div_ft4_3' class="collapse in" align="left">
    <pre>
    
ft4_3: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_05_invest.py", line 51, in test_register
    new_data = HandleContext().invest_param(val['data'])
  File "G:\qianchengdai\script\handle_context.py", line 147, in invest_param
    data = cls.loan_replace(data)
  File "G:\qianchengdai\script\handle_context.py", line 115, in loan_replace
    load_id = str(getattr(cls, "load_id"))
AttributeError: type object 'HandleContext' has no attribute 'load_id'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_4' class='none'>
    <td class='failCase'><div class='testcase'>test_register_04_投资人正常登录</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_4'>失败</button>
    <div id='div_ft4_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_4'>失败</button>
    <div id='div_ft4_4' class="collapse in" align="left">
    <pre>
    
ft4_4: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_05_invest.py", line 80, in test_register
    raise e
  File "G:\qianchengdai\cases\test_05_invest.py", line 73, in test_register
    self.assertEqual(str(val['expected']),code)
AssertionError: '10001' != '20111'
- 10001
+ 20111



    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_5' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_05_投资人正常投资</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_5'>错误</button>
    <div id='div_ft4_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_5'>错误</button>
    <div id='div_ft4_5' class="collapse in" align="left">
    <pre>
    
ft4_5: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_05_invest.py", line 51, in test_register
    new_data = HandleContext().invest_param(val['data'])
  File "G:\qianchengdai\script\handle_context.py", line 147, in invest_param
    data = cls.loan_replace(data)
  File "G:\qianchengdai\script\handle_context.py", line 115, in loan_replace
    load_id = str(getattr(cls, "load_id"))
AttributeError: type object 'HandleContext' has no attribute 'load_id'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_6' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_06_投资人id为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_6'>错误</button>
    <div id='div_ft4_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_6'>错误</button>
    <div id='div_ft4_6' class="collapse in" align="left">
    <pre>
    
ft4_6: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_05_invest.py", line 51, in test_register
    new_data = HandleContext().invest_param(val['data'])
  File "G:\qianchengdai\script\handle_context.py", line 147, in invest_param
    data = cls.loan_replace(data)
  File "G:\qianchengdai\script\handle_context.py", line 115, in loan_replace
    load_id = str(getattr(cls, "load_id"))
AttributeError: type object 'HandleContext' has no attribute 'load_id'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_7' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_07_投资人密码为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_7'>错误</button>
    <div id='div_ft4_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_7'>错误</button>
    <div id='div_ft4_7' class="collapse in" align="left">
    <pre>
    
ft4_7: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_05_invest.py", line 51, in test_register
    new_data = HandleContext().invest_param(val['data'])
  File "G:\qianchengdai\script\handle_context.py", line 147, in invest_param
    data = cls.loan_replace(data)
  File "G:\qianchengdai\script\handle_context.py", line 115, in loan_replace
    load_id = str(getattr(cls, "load_id"))
AttributeError: type object 'HandleContext' has no attribute 'load_id'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_8' class='none'>
    <td class='failCase'><div class='testcase'>test_register_08_标id为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_8' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_8'>失败</button>
    <div id='div_ft4_8' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_8' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_8'>失败</button>
    <div id='div_ft4_8' class="collapse in" align="left">
    <pre>
    
ft4_8: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_05_invest.py", line 80, in test_register
    raise e
  File "G:\qianchengdai\cases\test_05_invest.py", line 73, in test_register
    self.assertEqual(str(val['expected']),code)
AssertionError: '11003' != None


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_9' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_09_投资金额为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_9' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_9'>错误</button>
    <div id='div_ft4_9' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_9' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_9'>错误</button>
    <div id='div_ft4_9' class="collapse in" align="left">
    <pre>
    
ft4_9: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_05_invest.py", line 51, in test_register
    new_data = HandleContext().invest_param(val['data'])
  File "G:\qianchengdai\script\handle_context.py", line 147, in invest_param
    data = cls.loan_replace(data)
  File "G:\qianchengdai\script\handle_context.py", line 115, in loan_replace
    load_id = str(getattr(cls, "load_id"))
AttributeError: type object 'HandleContext' has no attribute 'load_id'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_10' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_10_投资人id为负数</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_10' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_10'>错误</button>
    <div id='div_ft4_10' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_10' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_10'>错误</button>
    <div id='div_ft4_10' class="collapse in" align="left">
    <pre>
    
ft4_10: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_05_invest.py", line 51, in test_register
    new_data = HandleContext().invest_param(val['data'])
  File "G:\qianchengdai\script\handle_context.py", line 147, in invest_param
    data = cls.loan_replace(data)
  File "G:\qianchengdai\script\handle_context.py", line 115, in loan_replace
    load_id = str(getattr(cls, "load_id"))
AttributeError: type object 'HandleContext' has no attribute 'load_id'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_11' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_11_投资人id为0</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_11' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_11'>错误</button>
    <div id='div_ft4_11' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_11' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_11'>错误</button>
    <div id='div_ft4_11' class="collapse in" align="left">
    <pre>
    
ft4_11: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_05_invest.py", line 51, in test_register
    new_data = HandleContext().invest_param(val['data'])
  File "G:\qianchengdai\script\handle_context.py", line 147, in invest_param
    data = cls.loan_replace(data)
  File "G:\qianchengdai\script\handle_context.py", line 115, in loan_replace
    load_id = str(getattr(cls, "load_id"))
AttributeError: type object 'HandleContext' has no attribute 'load_id'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_12' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_12_标id为负数</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_12' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_12'>错误</button>
    <div id='div_ft4_12' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_12' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_12'>错误</button>
    <div id='div_ft4_12' class="collapse in" align="left">
    <pre>
    
ft4_12: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_05_invest.py", line 51, in test_register
    new_data = HandleContext().invest_param(val['data'])
  File "G:\qianchengdai\script\handle_context.py", line 147, in invest_param
    data = cls.loan_replace(data)
  File "G:\qianchengdai\script\handle_context.py", line 115, in loan_replace
    load_id = str(getattr(cls, "load_id"))
AttributeError: type object 'HandleContext' has no attribute 'load_id'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_13' class='none'>
    <td class='failCase'><div class='testcase'>test_register_13_标id为0</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_13' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_13'>失败</button>
    <div id='div_ft4_13' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_13' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_13'>失败</button>
    <div id='div_ft4_13' class="collapse in" align="left">
    <pre>
    
ft4_13: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_05_invest.py", line 80, in test_register
    raise e
  File "G:\qianchengdai\cases\test_05_invest.py", line 73, in test_register
    self.assertEqual(str(val['expected']),code)
AssertionError: '11005' != None


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_14' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_14_投资人密码长度小于6</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_14' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_14'>错误</button>
    <div id='div_ft4_14' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_14' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_14'>错误</button>
    <div id='div_ft4_14' class="collapse in" align="left">
    <pre>
    
ft4_14: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_05_invest.py", line 51, in test_register
    new_data = HandleContext().invest_param(val['data'])
  File "G:\qianchengdai\script\handle_context.py", line 147, in invest_param
    data = cls.loan_replace(data)
  File "G:\qianchengdai\script\handle_context.py", line 115, in loan_replace
    load_id = str(getattr(cls, "load_id"))
AttributeError: type object 'HandleContext' has no attribute 'load_id'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_15' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_15_投资人密码长度大于18</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_15' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_15'>错误</button>
    <div id='div_ft4_15' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_15' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_15'>错误</button>
    <div id='div_ft4_15' class="collapse in" align="left">
    <pre>
    
ft4_15: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_05_invest.py", line 51, in test_register
    new_data = HandleContext().invest_param(val['data'])
  File "G:\qianchengdai\script\handle_context.py", line 147, in invest_param
    data = cls.loan_replace(data)
  File "G:\qianchengdai\script\handle_context.py", line 115, in loan_replace
    load_id = str(getattr(cls, "load_id"))
AttributeError: type object 'HandleContext' has no attribute 'load_id'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_16' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_16_投资金额为负数</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_16' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_16'>错误</button>
    <div id='div_ft4_16' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_16' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_16'>错误</button>
    <div id='div_ft4_16' class="collapse in" align="left">
    <pre>
    
ft4_16: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_05_invest.py", line 51, in test_register
    new_data = HandleContext().invest_param(val['data'])
  File "G:\qianchengdai\script\handle_context.py", line 147, in invest_param
    data = cls.loan_replace(data)
  File "G:\qianchengdai\script\handle_context.py", line 115, in loan_replace
    load_id = str(getattr(cls, "load_id"))
AttributeError: type object 'HandleContext' has no attribute 'load_id'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_17' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_17_投资金额为不能被100整除的数</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_17' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_17'>错误</button>
    <div id='div_ft4_17' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_17' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_17'>错误</button>
    <div id='div_ft4_17' class="collapse in" align="left">
    <pre>
    
ft4_17: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_05_invest.py", line 51, in test_register
    new_data = HandleContext().invest_param(val['data'])
  File "G:\qianchengdai\script\handle_context.py", line 147, in invest_param
    data = cls.loan_replace(data)
  File "G:\qianchengdai\script\handle_context.py", line 115, in loan_replace
    load_id = str(getattr(cls, "load_id"))
AttributeError: type object 'HandleContext' has no attribute 'load_id'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_18' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_18_投资人id不存在</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_18' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_18'>错误</button>
    <div id='div_ft4_18' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_18' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_18'>错误</button>
    <div id='div_ft4_18' class="collapse in" align="left">
    <pre>
    
ft4_18: Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_05_invest.py", line 51, in test_register
    new_data = HandleContext().invest_param(val['data'])
  File "G:\qianchengdai\script\handle_context.py", line 147, in invest_param
    data = cls.loan_replace(data)
  File "G:\qianchengdai\script\handle_context.py", line 115, in loan_replace
    load_id = str(getattr(cls, "load_id"))
AttributeError: type object 'HandleContext' has no attribute 'load_id'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_19' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_19_标id不存在</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_19' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_19'>错误</button>
    <div id='div_ft4_19' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_19' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_19'>错误</button>
    <div id='div_ft4_19' class="collapse in" align="left">
    <pre>
    
ft4_19: Expecting value: line 1 column 60 (char 59)
Traceback (most recent call last):
  File "G:\qianchengdai\script\handle_reques.py", line 30, in __call__
    data = json.loads(data) # 尝试转化为dict格式
  File "E:\python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "E:\python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "E:\python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 60 (char 59)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\qianchengdai\lib\ddt.py", line 165, in wrapper
    return func(self, *args, **kwargs)
  File "G:\qianchengdai\cases\test_05_invest.py", line 55, in test_register
    data=new_data)
  File "G:\qianchengdai\script\handle_reques.py", line 33, in __call__
    data = eval(data) # 转换为序列类型
  File "&lt;string&gt;", line 1
    {"memberId":72350,"password":"${invest_user_pwd}","loanId":${not_exited_loan_id},"amount":500}
                                                               ^
SyntaxError: invalid syntax


    </pre>
    </div>
    </td>
</tr>

<tr class='passClass warning'>
    <td>test__01_register.TestRegister</td>
    <td class="text-center">10</td>
    <td class="text-center">10</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center"><a href="javascript:showClassDetail('c5',10)" class="detail" id='c5'>详细</a></td>
</tr>

<tr id='pt5_1' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_register_01_成功注册_完整</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt5_2' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_register_02_成功注册_无昵称</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt5_3' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_register_03_成功注册_有昵称</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt5_4' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_register_04_密码为空</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt5_5' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_register_05_手机号为空</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt5_6' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_register_06_手机号_不足11位</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt5_7' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_register_07_手机号_超过11位</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt5_8' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_register_08_密码_少于6位</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt5_9' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_register_09_密码_多于18位</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt5_10' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_register_10_手机号已注册</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='total_row' class="text-center active">
    <td>总计</td>
    <td>65</td>
    <td>14</td>
    <td>37</td>
    <td>14</td>
    <td>通过率：21.54%</td>
</tr>
</table>

<div id='ending'>&nbsp;</div>
    <div style=" position:fixed;right:50px; bottom:30px; width:20px; height:20px;cursor:pointer">
    <a href="#"><span class="glyphicon glyphicon-eject" style = "font-size:30px;" aria-hidden="true">
    </span></a></div>
    
</body>
</html>
